### ISSUE TITLE
users password 

### ISSUE THREAD

**Issue by PinyBuom** [linuxmint/doc-installation-guide#6]
i forget my root password and how can i reset it

**Comment by BogTheMudWing** [comment]
Hi! This isn't the right place to ask for help. Try the [Linux Mint Forums](https://forums.linuxmint.com/) or the [Matrix room](https://matrix.to/#/#linuxmint:matrix.org) and someone might be able to help you out!

**Comment by BogTheMudWing** [comment]
This article may be helpful to you as well: https://linuxmint-user-guide.readthedocs.io/en/latest/lost-password.html
