### ISSUE TITLE
Create bootable media page links to update

### ISSUE THREAD

**Issue by gpcodeac** [linuxmint/doc-installation-guide#7]
This file:
https://github.com/linuxmint/doc-installation-guide/blob/master/docs/burn.rst

links to:
https://www.balena.io/etcher

which is outdated, perhaps. New link is: https://etcher.balena.io/

Also, tool UI has changed slightly so button names are also different.

![image](https://github.com/user-attachments/assets/dc5d6e68-6bf4-46a3-8815-165c5a81be6a)

**Comment by clefebvre** [comment]
Fixed
